substitutions:
  name: "weather-station"
  friendly_name: "Weather Station"

esphome:
  name: "${name}"

esp32:
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_weatherstation
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet
  ap:
    ssid: "${name}-AP"
    password: !secret wifi_password

captive_portal:

logger:
  level: DEBUG

api:

ota:

external_components:
  - source: local_components
    components: [ ulp_rain_meter ]

sensor:
  - platform: ulp_rain_meter
    name: Rain Meter
